# Generated by Django 4.1.7 on 2023-05-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Funcao',
            new_name='Cargo',
        ),
        migrations.RenameField(
            model_name='funcionario',
            old_name='funcao',
            new_name='cargo',
        ),
    ]
