# Generated by Django 4.2 on 2023-06-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_rename_funcao_cargo_rename_funcao_funcionario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='esta_logado',
            field=models.BooleanField(default=False),
        ),
    ]
