# Generated by Django 4.1.7 on 2023-05-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdvWeb', '0002_remove_venda_produto_remove_venda_qtd_itemvenda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='estoque',
            new_name='quantidade',
        ),
    ]
