# Generated by Django 4.2 on 2023-06-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvWeb', '0005_venda_cpf_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
