# Generated by Django 4.2 on 2023-06-09 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvWeb', '0006_venda_finalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 17, 26, 13, 813983, tzinfo=datetime.timezone.utc)),
        ),
    ]
