# Generated by Django 4.2 on 2023-06-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdvWeb', '0012_alter_venda_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='data',
            field=models.CharField(max_length=255),
        ),
    ]
